### ISSUE TITLE
Can't access Disc for some reason, general inquiry r/t getting OmniCC timers for buffs/debuffs:

### ISSUE THREAD

**Issue by Lexlutheran** [XyzKangUI/RougeUI#2]
Hey, since I don't think you're likely to port this addon to retail anytime soon given the scope it entails I just wanted to ask how you managed to get OmniCC timers working on buffs/debuffs if that's something you're able/willing to share. Tried digging thru most of the lua files to see if I could figure it out, but I'm pretty out of the know when it comes to this kind of shit. Appreciate any help and NBD if you can't be asked.

**Comment by XyzKangUI** [comment]
> Hey, since I don't think you're likely to port this addon to retail anytime soon given the scope it entails I just wanted to ask how you managed to get OmniCC timers working on buffs/debuffs if that's something you're able/willing to share. Tried digging thru most of the lua files to see if I could figure it out, but I'm pretty out of the know when it comes to this kind of shit. Appreciate any help and NBD if you can't be asked.

It was in this update https://github.com/XyzKangUI/RougeUI/commit/eb07c855359ac5d2fafd465ca62c2f42509b6de1#diff-3f66f406f1d025f676a3da0f3ebb3954e94deea45423d559871a5da0b5cc9b36R154
