### ISSUE TITLE
reTABbinder doesnt work

### ISSUE THREAD

**Issue by HuMa69** [XyzKangUI/RougeUI#5]
hi, the retabind doesnt work in arenas, i know well this "addon" because i used it on retail, it keeps targeting totems and pets when i tab in arena and BGs, can you check it?

**Comment by XyzKangUI** [comment]
> hi, the retabind doesnt work in arenas, i know well this "addon" because i used it on retail, it keeps targeting totems and pets when i tab in arena and BGs, can you check it?

You are right, there is a typo in the settings somehow. Good catch.
