### ISSUE TITLE
Hightlight Magic Buffs Classic SoD

### ISSUE THREAD

**Issue by zirtox1992** [XyzKangUI/RougeUI#6]
The border of the highlight is way too big compared to the buff or debuff
![asfsfasfsfa](https://github.com/XyzKangUI/RougeUI/assets/50052382/e230c69f-f87f-4342-a444-0d3128dff990)

**Comment by XyzKangUI** [comment]
> The border of the highlight is way too big compared to the buff or debuff

I believe you are using an other addon that changes the size of the buff, which causes the difference.

![image](https://github.com/XyzKangUI/RougeUI/assets/94811434/146db5d3-5b7e-43c1-8fe5-04596172d007)
