### ISSUE TITLE
3.3.5

### ISSUE THREAD

**Issue by Hannahmckayx** [XyzKangUI/RougeUI#8]
The script to hide server names is buggy in 3.3.5 so I deleted it:(CompactRaidFrames)

https://imgur.com/a/KGZi3av

EDIT: And another bug I found was that gladdy doesn't show the totems icon.(both friends/enemies):

https://imgur.com/LKEvgxC

**Comment by XyzKangUI** [comment]
Error with the thing is due to some API not existing on client, thanks. The bug with Gladdy you can direct to whoever maintain it on 3.3.5, but I am sure they won't bother because to get it working you need FrostAtom's awesomewotlk and I don't think addons adapt to it.
